<a href="https://colab.research.google.com/github/Facco-Bruno/Alura-Python/blob/Master/Functions%2C_dicts%2C_lists_for_data_science.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np

In [3]:
dataset = pd.read_csv('db.csv', sep = ';')
dataset

                      Nome  ...      Valor
0            Jetta Variant  ...   88078.64
1                   Passat  ...  106161.94
2                 Crossfox  ...   72832.16
3                      DS5  ...  124549.07
4         Aston Martin DB4  ...   92612.10
..                     ...  ...        ...
253           Phantom 2013  ...   51759.58
254  Cadillac Ciel concept  ...   51667.06
255             Classe GLK  ...   68934.03
256       Aston Martin DB5  ...  122110.90
257                  Macan  ...   90381.47

[258 rows x 7 columns]

In [4]:
import pandas as pd
pd.set_option('display.max_rows', 1000)

In [5]:
dataset.dtypes

Nome              object
Motor             object
Ano                int64
Quilometragem    float64
Zero_km             bool
Acessórios        object
Valor            float64
dtype: object

In [6]:
dataset[['Quilometragem', 'Valor']].describe()

       Quilometragem          Valor
count     197.000000     258.000000
mean    58278.421320   98960.513101
std     35836.733259   29811.932305
min       107.000000   50742.100000
25%     27505.000000   70743.512500
50%     55083.000000   97724.380000
75%     90495.000000  124633.302500
max    119945.000000  149489.920000

In [7]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 258 entries, 0 to 257
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Nome           258 non-null    object
 1   Motor          258 non-null    object
 2   Ano            258 non-null    int64
 3   Quilometragem  197 non-null    float64
 4   Zero_km        258 non-null    bool
 5   Acessórios     258 non-null    object
 6   Valor          258 non-null    float64
dtypes: bool(1), float64(2), int64(1), object(3)
memory usage: 12.5+ KB

In [8]:
carros = ['Jetta Variant', 'Passat', 'Crossfox', 'DS5']
carros

['Jetta Variant', 'Passat', 'Crossfox', 'DS5']

In [9]:
valores = [88078.64, 106161.94, 72832.16, 124549.07]
valores

[88078.64, 106161.94, 72832.16, 124549.07]

In [10]:
zip(carros, valores)

In [11]:
list(zip(carros, valores))

[('Jetta Variant', 88078.64),
 ('Passat', 106161.94),
 ('Crossfox', 72832.16),
 ('DS5', 124549.07)]

In [12]:
for carro, valor in zip(carros, valores):
  print(carro, valor)

Jetta Variant 88078.64
Passat 106161.94
Crossfox 72832.16
DS5 124549.07

In [13]:
for carro, valor in zip(carros, valores):
  if(valor > 100000):
    print(carro)

Passat
DS5

In [14]:
dados = {'Crossfox': 72832.16, 'DS5': 124549.07,  'Fusca': 150000,  'Jetta Variant': 88078.64,  'Passat': 106161.95}
dados

{'Crossfox': 72832.16,
 'DS5': 124549.07,
 'Fusca': 150000,
 'Jetta Variant': 88078.64,
 'Passat': 106161.95}

In [15]:
dados.keys()

dict_keys(['Crossfox', 'DS5', 'Fusca', 'Jetta Variant', 'Passat'])

In [16]:
for key in dados.keys():
  print(dados[key])

72832.16
124549.07
150000
88078.64
106161.95

In [17]:
dados.values()

dict_values([72832.16, 124549.07, 150000, 88078.64, 106161.95])

In [18]:
for item in dados.items():
    print(item)

('Crossfox', 72832.16)
('DS5', 124549.07)
('Fusca', 150000)
('Jetta Variant', 88078.64)
('Passat', 106161.95)

In [19]:
for key, value in dados.items():
    print(key, value)

Crossfox 72832.16
DS5 124549.07
Fusca 150000
Jetta Variant 88078.64
Passat 106161.95

In [20]:
for key, value in dados.items():
  if (value > 100000):
    print(key)

DS5
Fusca
Passat

In [21]:
dados = {'Crossfox': {'km': 35000, 'ano': 2005, 'km_media': 2500.0},
 'DS5': {'km': 17000, 'ano': 2015, 'km_media': 4250.0},
 'Fusca': {'km': 130000, 'ano': 1979, 'km_media': 3250.0},
 'Jetta': {'km': 56000, 'ano': 2011, 'km_media': 7000.0},
 'Passat': {'km': 62000, 'ano': 1999, 'km_media': 3100.0}}

In [24]:
df = pd.DataFrame(dados)
df

          Crossfox      DS5     Fusca    Jetta   Passat
km         35000.0  17000.0  130000.0  56000.0  62000.0
ano         2005.0   2015.0    1979.0   2011.0   1999.0
km_media    2500.0   4250.0    3250.0   7000.0   3100.0

In [25]:
df = pd.DataFrame(dados).T
df

                km     ano  km_media
Crossfox   35000.0  2005.0    2500.0
DS5        17000.0  2015.0    4250.0
Fusca     130000.0  1979.0    3250.0
Jetta      56000.0  2011.0    7000.0
Passat     62000.0  1999.0    3100.0

In [26]:
import pandas as pd

dados = {
    'Nome': ['Jetta', 'Passat', 'Crossfox', 'DS5', 'Fusca'], 
    'Motor': ['Motor 4.0 Turbo', 'Motor Diesel', 'Motor Diesel V8', 'Motor 2.0', 'Motor 1.6'],
    'Ano': [2019, 2003, 1991, 2019, 1990],
    'Quilometragem': [0.0, 5712.0, 37123.0, 0.0, 120000.0],
    'Zero_km': [True, False, False, True, False],
    'Valor': [88000.0, 106000.0, 72000.0, 89000.0, 32000.0]
}

dataset = pd.DataFrame(dados)

In [27]:
dataset

       Nome            Motor   Ano  Quilometragem  Zero_km     Valor
0     Jetta  Motor 4.0 Turbo  2019            0.0     True   88000.0
1    Passat     Motor Diesel  2003         5712.0    False  106000.0
2  Crossfox  Motor Diesel V8  1991        37123.0    False   72000.0
3       DS5        Motor 2.0  2019            0.0     True   89000.0
4     Fusca        Motor 1.6  1990       120000.0    False   32000.0

In [28]:
dataset[1:3][['Nome', 'Ano', 'Quilometragem', 'Valor']]

       Nome   Ano  Quilometragem     Valor
1    Passat  2003         5712.0  106000.0
2  Crossfox  1991        37123.0   72000.0

In [29]:
import pandas as pd

dados = {
    'Motor': ['Motor 4.0 Turbo', 'Motor Diesel', 'Motor Diesel V8', 'Motor 2.0', 'Motor 1.6'],
    'Ano': [2019, 2003, 1991, 2019, 1990],
    'Quilometragem': [0.0, 5712.0, 37123.0, 0.0, 120000.0],
    'Zero_km': [True, False, False, True, False],
    'Valor': [88000.0, 106000.0, 72000.0, 89000.0, 32000.0]
}

dataset = pd.DataFrame(dados, index = ['Jetta', 'Passat', 'Crossfox', 'DS5', 'Fusca'])

In [30]:
dataset

                    Motor   Ano  Quilometragem  Zero_km     Valor
Jetta     Motor 4.0 Turbo  2019            0.0     True   88000.0
Passat       Motor Diesel  2003         5712.0    False  106000.0
Crossfox  Motor Diesel V8  1991        37123.0    False   72000.0
DS5             Motor 2.0  2019            0.0     True   89000.0
Fusca           Motor 1.6  1990       120000.0    False   32000.0

In [31]:
import pandas as pd

dados = {
    'Motor': ['Motor 4.0 Turbo', 'Motor Diesel', 'Motor Diesel V8', 'Motor Diesel', 'Motor 1.6'],
    'Ano': [2019, 2003, 1991, 2019, 1990],
    'Quilometragem': [0.0, 5712.0, 37123.0, 0.0, 120000.0],
    'Zero_km': [True, False, False, True, False],
    'Valor': [88000.0, 106000.0, 72000.0, 89000.0, 32000.0]
}

dataset = pd.DataFrame(dados, index = ['Jetta', 'Passat', 'Crossfox', 'DS5', 'Fusca'])

In [32]:
dataset

                    Motor   Ano  Quilometragem  Zero_km     Valor
Jetta     Motor 4.0 Turbo  2019            0.0     True   88000.0
Passat       Motor Diesel  2003         5712.0    False  106000.0
Crossfox  Motor Diesel V8  1991        37123.0    False   72000.0
DS5          Motor Diesel  2019            0.0     True   89000.0
Fusca           Motor 1.6  1990       120000.0    False   32000.0

Da pra usar o loc para criar uma coluna nova quando ele não reconhece, usando um iterador entre o indice e as linhas do dataset

for index, row in dataset.iterrows():
  if(2019 - row['Ano'] != 0):
    dataset.loc[index, 'Km_media'] = row['Quilometragem'] / (2019 - row['Ano'])
  else:
    dataset.loc[index, 'Km_media'] = 0

dataset

In [33]:
dataset = pd.read_csv('db.csv', sep = ';')

In [39]:
#dataset.info

In [35]:
dataset.head()

               Nome  ...      Valor
0     Jetta Variant  ...   88078.64
1            Passat  ...  106161.94
2          Crossfox  ...   72832.16
3               DS5  ...  124549.07
4  Aston Martin DB4  ...   92612.10

[5 rows x 7 columns]

In [36]:
dataset.dropna(subset = ['Quilometragem'], inplace = True)

In [37]:
dataset

                                       Nome  ...      Valor
0                             Jetta Variant  ...   88078.64
1                                    Passat  ...  106161.94
2                                  Crossfox  ...   72832.16
4                          Aston Martin DB4  ...   92612.10
5                             Palio Weekend  ...   97497.73
7                            Série 3 Cabrio  ...  112310.44
8                              Dodge Jorney  ...  120716.27
9                                    Carens  ...   76566.49
10                                Ford Edge  ...   71647.59
11                                  Courier  ...   73919.53
12                                     S-18  ...  112732.99
14                             F-Type Coupé  ...  127488.42
15                                      RAM  ...   59910.40
16                                  Série 1  ...   61118.59
18                                     XC90  ...   62696.69
19                           RS 3 Sportback  ...  101726.30
20                             Pajero Sport  ...  106147.38
22                      Lamborghini Obvious  ...  133529.84
23                    Effa Hafei Picape Baú  ...  125684.65
26                       Fiesta Rocam Sedan  ...   95347.75
28                                 Cayman S  ...   57045.27
29                                      V40  ...  120432.70
30                           Classe SLS AMG  ...   70707.20
31                                   Gol G4  ...   69105.18
32                                    Linea  ...   59358.69
33                                Ford F100  ...   65955.40
34                                       J2  ...   60017.03
35                         Aston Martin DBS  ...  118909.52
38                               California  ...   69770.18
40                                   Tucson  ...   67997.19
41                                     HB20  ...  135235.29
43                                    Logan  ...  136818.39
45                                   Sonata  ...   56208.70
46                    Ford New Fiesta Sedan  ...   84222.65
47                     Série 5 Gran Turismo  ...   90781.65
49                            Ford EcoSport  ...  126350.49
50                                    Versa  ...  148152.89
51                                 Classe E  ...  132298.83
52                                 Carnival  ...  137627.63
53         Aston Martin V8 Vantage Roadster  ...   80422.71
54                                   Hoggar  ...   56373.99
55                                       A1  ...   70846.03
56                 Aston Martin DB7 Vantage  ...  128694.23
62                         New Fiesta Hatch  ...   66007.16
63                            Jeep Renegade  ...  128776.22
64                     Lamborghini Ankonian  ...  142623.02
65                              Space Cross  ...  136930.13
67                                 Classe M  ...  114154.87
69                           Kangoo Express  ...  146716.91
70                                      SW4  ...  122485.68
71                             Cadillac ELR  ...   97951.03
72                                    Doblò  ...   78283.49
73                      Lamborghini Egoista  ...   83434.04
74                                      Fit  ...   77836.23
75                                       C5  ...   60813.92
76                              Celer Hatch  ...   91353.86
77                                    HB20S  ...  116281.21
80                                   Ducato  ...   73033.53
81                                    March  ...   54332.87
82                       Cadillac XTS sedan  ...   52207.45
83                   Lamborghini Centenario  ...   63578.50
86                                   Symbol  ...  133030.60
87               Aston Martin V12 GT Zagato  ...  141591.86
89                                 A4 Sedan  ...   96369.04
90                            Xsara Picasso  ...  142603.84
91                                   207 SW  ...  117709.67
92                                     Star  ...  102241.54
93                              Doblò Cargo  ...   96065.38
94                             Cadillac CTS  ...   53894.61
95                                  Cayenne  ...  123911.78
96                                      Fox  ...  101996.35
97                              Tiida Hatch  ...   83431.66
98                            Dodge Charger  ...  122975.63
100                                   Prius  ...   58762.65
101                                    Idea  ...  139549.67
103                          Série 1 Cabrio  ...   72731.98
104                                    Edge  ...   88416.54
105                      Cadillac ATS sedan  ...   73873.42
106          Lamborghini Asterion LPI 910-4  ...   70709.34
107                                Frontier  ...  115306.50
108                            Série 3 Sedã  ...   55924.63
109                       Lamborghini LM002  ...   85052.26
110                            Cadillac XLR  ...   56646.34
111                                A4 Avant  ...  138946.88
112                                EcoSport  ...  108256.72
113                                      J3  ...   58979.30
115                 Aston Martin V8 Vantage  ...  139661.48
118                                Ford Ka+  ...   87830.41
119                           Silver Shadow  ...  143568.22
120                 Classe C 63 AMG Touring  ...  138171.85
121                             Discovery 4  ...  115784.95
122                                Veloster  ...  146508.99
123                                Classe C  ...  137670.23
125                               C5 Tourer  ...  147627.81
127                                   Bongo  ...   91242.44
128                                     ASX  ...  149489.92
129                            Cadillac SRX  ...   63529.95
131                              500 Abarth  ...   90345.05
133                            Cadillac STS  ...  106617.71
134                        Aston Martin DB9  ...  104929.88
135                                 NX 200t  ...  100712.45
136                     Aston Martin One-77  ...  141982.93
138                                  Sentra  ...   88501.54
139                                  Jumper  ...   79782.02
141                                      X6  ...  103596.18
144                          Passat Variant  ...   69535.44
145                                    Clio  ...  111130.33
146                                Classe G  ...   65847.69
147                            Silver Ghost  ...   78096.06
148                        Série 3 M3 Coupé  ...   69219.89
149                     Gallardo LP 560 – 4  ...  144118.91
150                            Freelander 2  ...   77397.05
151                          Grand Cherokee  ...   68974.25
152                       Aston Martin DBR9  ...  125231.30
153                                    Soul  ...   85501.12
154                            Cadillac BLS  ...  137116.21
155                                  RX 350  ...  138823.81
156                                  Cayman  ...  117961.95
157                           Chana Utility  ...  132662.32
160                                   Jetta  ...  140934.60
161                               C4 Lounge  ...   82366.81
162                               C4 Pallas  ...   70424.11
163                                   Equus  ...   53620.31
164                               Classe GL  ...   73389.18
165                      Range Rover Evoque  ...  111618.12
166                                Cherokee  ...  112187.37
167                                   Punto  ...  120812.57
168                              Grand Tour  ...  116031.04
169                                 Fluence  ...  125398.11
170        Effa Hafei Picape Cabine Simples  ...   76101.47
171                                 Durango  ...   75263.24
172                                 Boxster  ...  147387.76
173                             TT Roadster  ...   85311.40
174                       Lamborghini Jalpa  ...   54388.11
176                                    Golf  ...  146203.34
178                                     V50  ...   68873.79
179                                 Picanto  ...   91667.61
180                                 Cadenza  ...   93776.52
181                              Etios Sedã  ...   66433.82
182                                  Alsvin  ...  109059.27
183                            Cadillac ATS  ...  122069.97
184                         Série 3 M3 Sedã  ...  113090.32
187                        Aston Martin DB7  ...  146676.71
188                               207 Sedan  ...   89511.96
190                                   Azera  ...  120673.56
192                                Siena EL  ...  139546.69
193                         Palio Adventure  ...   95078.16
194                                   HB20X  ...   68091.77
195                                      HR  ...   61496.97
196                   Cadillac STS V-Series  ...  139669.30
197                           Série 1 Coupé  ...   80661.39
198                                SpaceFox  ...   61783.65
199                                     C30  ...   52805.91
203                   Cadillac CTS V-Series  ...  107342.68
205                       Classe CLS 63 AMG  ...  118161.48
206                                Aircross  ...  142499.06
208                                 Sandero  ...  112350.61
209                              New Fiesta  ...  124661.38
210                                     XKR  ...   54263.16
211                                      X5  ...   62041.32
212                            Cadillac DTS  ...  129296.11
213                            Pajero Dakar  ...   60998.33
214                                Classe A  ...   58008.50
215                     Ford Focus Fastback  ...   82304.19
217                                      R8  ...  128565.61
218                Aston Martin DBS Volante  ...  126488.26
219                                  Mohave  ...  119074.55
220                                   Fusca  ...  130238.04
222                                    XC40  ...  121248.00
223  Phantom I Jonckheere Aerodynamic Coupe  ...   98156.35
224                                   Boxer  ...  112146.80
225                             Chana Cargo  ...  102729.63
226                            Dodge Dakota  ...  141083.35
227                                      X1  ...  102968.76
228                                     GLA  ...   76310.01
229                       Range Rover Sport  ...  120481.74
230                                     DS3  ...   54559.18
231                                Veracruz  ...   92957.64
232    Cadillac CTS coupe, sedan, and wagon  ...  127810.06
233                                  i30 CW  ...   73311.75
234                             Phantom III  ...   65138.03
236                Aston Martin DB9 Volante  ...   71160.36
239                            Grand Livina  ...   68652.16
240                                     V60  ...  114728.74
241          Effa Hafei Picape Cabine Dupla  ...  141645.08
244                             L200 Savana  ...  132384.76
246                                     RS5  ...   89536.82
247                                  Cerato  ...   87975.30
249                                 LS 460L  ...   58881.67
250              Lamborghini Sesto Elemento  ...   55081.99
251                     Lamborghini Huracán  ...  118826.44
252                                      A7  ...  137627.62
253                            Phantom 2013  ...   51759.58
254                   Cadillac Ciel concept  ...   51667.06
255                              Classe GLK  ...   68934.03
256                        Aston Martin DB5  ...  122110.90
257                                   Macan  ...   90381.47

[197 rows x 7 columns]

In [38]:
dataset[dataset.Quilometragem.isna()]

Empty DataFrame
Columns: [Nome, Motor, Ano, Quilometragem, Zero_km, Acessórios, Valor]
Index: []

In [40]:
dataset.Quilometragem.isna()

0      False
1      False
2      False
4      False
5      False
7      False
8      False
9      False
10     False
11     False
12     False
14     False
15     False
16     False
18     False
19     False
20     False
22     False
23     False
26     False
28     False
29     False
30     False
31     False
32     False
33     False
34     False
35     False
38     False
40     False
41     False
43     False
45     False
46     False
47     False
49     False
50     False
51     False
52     False
53     False
54     False
55     False
56     False
62     False
63     False
64     False
65     False
67     False
69     False
70     False
71     False
72     False
73     False
74     False
75     False
76     False
77     False
80     False
81     False
82     False
83     False
86     False
87     False
89     False
90     False
91     False
92     False
93     False
94     False
95     False
96     False
97     False
98     False
100    False
101    False
103    False
104    False
105    False
106    False
107    False
108    False
109    False
110    False
111    False
112    False
113    False
115    False
118    False
119    False
120    False
121    False
122    False
123    False
125    False
127    False
128    False
129    False
131    False
133    False
134    False
135    False
136    False
138    False
139    False
141    False
144    False
145    False
146    False
147    False
148    False
149    False
150    False
151    False
152    False
153    False
154    False
155    False
156    False
157    False
160    False
161    False
162    False
163    False
164    False
165    False
166    False
167    False
168    False
169    False
170    False
171    False
172    False
173    False
174    False
176    False
178    False
179    False
180    False
181    False
182    False
183    False
184    False
187    False
188    False
190    False
192    False
193    False
194    False
195    False
196    False
197    False
198    False
199    False
203    False
205    False
206    False
208    False
209    False
210    False
211    False
212    False
213    False
214    False
215    False
217    False
218    False
219    False
220    False
222    False
223    False
224    False
225    False
226    False
227    False
228    False
229    False
230    False
231    False
232    False
233    False
234    False
236    False
239    False
240    False
241    False
244    False
246    False
247    False
249    False
250    False
251    False
252    False
253    False
254    False
255    False
256    False
257    False
Name: Quilometragem, dtype: bool

Usando query podemos trazer informações sobre o dataframe usando o nome das colunas e um interador de igualdade e também elementos de comparação